dist: trusty
sudo: required
services:
  - docker
language: go
go:
- "1.11.1"

go_import_path: github.com/ucloud/ucloud-sdk-go

git:
  depth: 1

install:
- go get github.com/fzipp/gocyclo

script:
- make fmtcheck
- make test
# - make cyclo

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
